inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
Style/Documentation:
  Description: 'Document classes and non-namespace modules'
  Enabled: false
